//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quiz.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Direcciones
    {
        public int id { get; set; }
        public int id_Persona { get; set; }
        public string pais { get; set; }
        public string provincia { get; set; }
        public string canton { get; set; }
        public string distrito { get; set; }
        public string detalles { get; set; }
    
        public virtual Datos_Personales Datos_Personales { get; set; }
    }
}
